import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/Nav/Nav'
import About from '../components/About/About'
import styles from '../styles/Home.module.scss'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				{/* rick roll */}
				{/* <meta httpEquiv = "refresh" content = "0; url = https://youtu.be/dQw4w9WgXcQ" /> */}
				<title>fauwara</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.container}>
				<Nav />
				<div className={styles.main}>
					<About />
				</div>
			</main>
		</div>
	)
}
